### ISSUE TITLE
Image resolution question

### ISSUE THREAD

**Issue by franeknowak** [CAMMA-public/SurgLatentGraph#1]
Hello,
I'm looking for information on what is the resolution of the images used to train your models. I found information that your aspect ratio is 2:3 (at least for Endoscapes-DeepCVS), but I don't know the exact resolution, and whether that also applies to other models?
Thank you!
Franek

**Comment by adit98** [comment]
Hi Franek,

All the models ingest images with size 224x399. You can see this in the dataset config files ([Endoscapes](https://github.com/CAMMA-public/SurgLatentGraph/blob/main/configs/datasets/endoscapes/endoscapes_instance.py)).

The 2:3 aspect ratio is an input to the SPADE reconstruction module, and corresponds to the aspect ratio of the reconstructed images (which have size 64x96). This is detailed in the LG-CVS paper.

Hope this helps!

**Comment by franeknowak** [comment]
Absolutely helps, thank you for a quick response :)
Best
