### ISSUE TITLE
How would we get the latent temporal graphs (with the nodal and edge attributes)?

### ISSUE THREAD

**Issue by cypher004** [CAMMA-public/SurgLatentGraph#2]
How would we access (externally save) the latent temporal graphs e.g. from LV2stg?

For example the non temporal graph have the visualizer which saves and draws them. 

Thanks

label:help-wanted

**Comment by adit98** [comment]
Hi,

We haven't implemented a visualizer for the spatio-temporal latent graphs at the moment - the visualizations in our paper were done manually.

We will try to implement and push one, but it might take some time. We would also welcome any pull requests.
