### ISSUE TITLE
CholecT50 dataset setup

### ISSUE THREAD

**Issue by Ethan13Young** [CAMMA-public/SurgLatentGraph#4]
Hi, the readme data setup section specifies cholecT50 needs to be extracted as 25fps, however the dataset itself (according to the link provided) are already frames extracted in 1fps.

**Comment by adit98** [comment]
Hi, thanks for raising the issue. So for the CholecT50 setup, you should be able to rename the frames provided in the dataset according to their respective frame number in 25fps (so `0.jpg -> 0.jpg`, `1.jpg -> 25.jpg`, etc.). The temporal models are generally only trained with 1fps granularity so there shouldn't be any issues.

Apologies for the oversight!

**Comment by Ethan13Young** [comment]
Thank you for your prompt reply! Issue closed
