### ISSUE TITLE
unable to import custom packages/models

### ISSUE THREAD

**Issue by cypher004** [CAMMA-public/SurgLatentGraph#6]
I've set up the environment as specified, including setting up the PYTHONPATH and MMDETECTION environment variables (the report path in the error also reflects this). Despite this the sample code is unable to find/import the custom models, file and datasets.

Would appreciate any help. It may just be very newbie/unfamiliar with mmlab error.

```

ImportError: Failed to import custom modules from {'imports': ['datasets.custom_loading', 'model.lg', 'evaluator.CocoMetricRGD'], 'allow_failed_imports': False}, the current sys.path is: 
    /home/vivari/miniconda3/envs/latentgraph2/lib/python3.8/site-packages/mmdet/.mim/tools
    **/home/vivari/codetest/surgvid/svidtry2/SurgLatentGraph**
    /home/vivari/miniconda3/envs/latentgraph2/lib/python38.zip
    /home/vivari/miniconda3/envs/latentgraph2/lib/python3.8
    /home/vivari/miniconda3/envs/latentgraph2/lib/python3.8/lib-dynload
    /home/vivari/miniconda3/envs/latentgraph2/lib/python3.8/site-packages
    /tmp/tmp63d3x51g
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module
```

python 3.8/conda env/packages:
`
libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.15.2                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.5                   pypi_0    pypi
annotated-types           0.6.0            py38h06a4308_0  
blas                      1.0                         mkl  
brotli-python             1.0.9            py38h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.3.2              pyhd3eb1b0_0  
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              43.0.1                   pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.6                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
dgl                       1.1.2.cu118              py38_0    dglteam/label/cu118
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.14.0                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
fsspec                    2024.9.0           pyhff2d567_0    conda-forge
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py38heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
idna                      3.7              py38h06a4308_0  
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib-resources       6.4.5                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.4            py38h06a4308_0  
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h5eee18b_3  
kiwisolver                1.4.7                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libabseil                 20240116.2      cxx17_he02047a_1    conda-forge
libblas                   3.9.0            20_linux64_mkl    conda-forge
libcblas                  3.9.0            20_linux64_mkl    conda-forge
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.11.1.6                      0    nvidia
libcurand                 10.3.7.68                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libffi                    3.4.4                h6a678d5_1  
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   14.1.0               h77fa898_1    conda-forge
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libprotobuf               4.25.3               h08a7969_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libtorch                  2.1.2           cpu_mkl_hff68eba_104    conda-forge
libunistring              0.9.10               h27cfd23_0  
libuv                     1.48.0               hd590300_0    conda-forge
libwebp-base              1.3.2                h5eee18b_0  
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lightning-utilities       0.11.7             pyhd8ed1ab_0    conda-forge
llvm-openmp               18.1.4               ha31de31_0    conda-forge
lz4-c                     1.9.4                h6a678d5_1  
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3            py38h5eee18b_0  
matplotlib                3.7.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.2.0         h84fe81f_50496    conda-forge
mkl-service               2.4.0            py38h5eee18b_1  
mkl_fft                   1.3.8            py38h5eee18b_0  
mkl_random                1.2.4            py38hdb19cb5_0  
mmcv                      2.1.0                    pypi_0    pypi
mmdet                     3.2.0                    pypi_0    pypi
mmengine                  0.7.4                    pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0            py38h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numpy                     1.24.3           py38hf6e8229_1  
numpy-base                1.24.3           py38h060ed82_1  
opencv-python             4.10.0.84                pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.5.2                he7f1fd0_0  
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.3.2                hb9d3cd8_0    conda-forge
openxlab                  0.1.1                    pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.1             py38h06a4308_0  
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.4.0           py38h5eee18b_0  
pip                       24.2             py38h06a4308_0  
platformdirs              3.10.0           py38h06a4308_0  
pooch                     1.7.0            py38h06a4308_0  
prettytable               3.11.0             pyhd8ed1ab_0    conda-forge
psutil                    5.9.0            py38h5eee18b_0  
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.8.2            py38h06a4308_0  
pydantic-core             2.20.1           py38hb02cf49_0  
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.19               h955ad1f_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   2.1.2           cpu_mkl_py38h1c8c993_104    conda-forge
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.4                   pypi_0    pypi
pyyaml                    6.0.1            py38h5eee18b_0  
readline                  8.2                  h5eee18b_0  
requests                  2.28.2                   pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
scikit-learn              1.3.2            py38ha25d942_2    conda-forge
scipy                     1.10.1           py38hf6e8229_1  
setuptools                60.2.0                   pypi_0    pypi
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sleef                     3.7                  h1b44611_0    conda-forge
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.13.2           py38h06a4308_0  
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
termcolor                 2.4.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tk                        8.6.14               h39e8969_0  
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
torch-scatter             2.1.1            py38h2fb5205_4    conda-forge
torchaudio                2.1.2                py38_cu118    pytorch
torchmetrics              1.4.2              pyhd8ed1ab_0    conda-forge
torchtriton               2.1.0                      py38    pytorch
torchvision               0.16.2               py38_cu118    pytorch
tqdm                      4.65.2                   pypi_0    pypi
typing-extensions         4.11.0           py38h06a4308_0  
typing_extensions         4.11.0           py38h06a4308_0  
tzdata                    2024.1                   pypi_0    pypi
urllib3                   1.26.20                  pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.44.0           py38h06a4308_0  
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.40.2                   pypi_0    pypi
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.5                hc292b87_2  
`

**Comment by adit98** [comment]
Could you provide the command you are running? Also what is directory are you running it from?

**Comment by cypher004** [comment]
Of course, its almost verbatim from the examples

```
$PYTHONPATH = /home/vivari/codetest/surgvid/svidtry2/SurgLatentGraph
$HOME = /home/vivari/codetest/surgvid/svidtry2
$MMDETECTION = /home/vivari/codetest/surgvid/svidtry2/mmdetection
pwd = /home/vivari/codetest/surgvid/svidtry2/SurgLatentGraph

mim train mmdet configs/models/faster_rcnn/lg_faster_rcnn.py
```

**Comment by adit98** [comment]
I'm not sure exactly what's going on, but perhaps try cloning the repositories directly into your home directory rather than redefining the `$HOME` environment variable?

**Comment by cypher004** [comment]
Just tried. Unfortunately am getting same the same errors. :(

**Comment by adit98** [comment]
Ok, one thing to try is to directly import a custom model from the `/home/vivari/codetest/surgvid/svidtry2/SurgLatentGraph` directory in the python shell. If that doesn't work, then we can isolate the issue to the `$PYTHONPATH` env variable.

So, making sure your conda environment is active, after running `export PYTHONPATH=$PYTHONPATH:/home/vivari/codetest/surgvid/svidtry2/SurgLatentGraph`, open a python shell and try the following:

`from model.lg import LGDetector`
