### ISSUE TITLE
File not found error when training deformable-Deter object detector

### ISSUE THREAD

**Issue by Ethan13Young** [CAMMA-public/SurgLatentGraph#7]
Training  deformable-Deter object detector will induce file not found issue
Specifically ~/mmdetection/configs/deformable_detr/deformable-detr_r50_16xb2-50e_coco_no_base.py" 
Exist files at location are
File1: ~/mmdetection/configs/deformable_detr/deformable-detr_r50_16xb2-50e_coco.py
File2: ~/mmdetection/configs/deformable_detr/deformable-detr-refine_r50_16xb2-50e_coco.py
File3: ~/mmdetection/configs/deformable_detr/deformable-detr-refine-twostage_r50_16xb2-50e_coco.py

Replacing relevant path with other file in code below (lg_def_detr.py in configs/models/def_detr/lg_def_detr.py)  would trigger other issues
_base_=['../lg_base_box.py',
    os.path.expandvars('$MMDETECTION/configs/deformable_detr/deformable-detr_r50_16xb2-50e_coco_no_base.py'),
]
File1: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3844_464/tmpq43clhny.py'
File2: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpt9slb6g8/tmpx4i8aqw_.py'
File3: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmptf81tiaj/tmpdmt45x81.py'

Perhaps deformable-detr_r50_16xb2-50e_coco_no_base.py is customised config script? (since readme of deformable_detr also did not mention this config...)

**Comment by adit98** [comment]
Thanks for bringing up the issue - I've pushed this config (as well as one for Mask2Former) to the `configs/_base_` directory and modified all configs to read from the new path. Should work now.

Cheers!
